---
- name: Combine CBS Storage Provisioning Playbooks
  hosts: all
  connection: local
  gather_facts: no

- import_playbook: collectportinfo.yaml
- import_playbook: create_volume.yaml
  #- import_playbook: open-iscsi.yaml
- import_playbook: create_host.yaml
  #- import_playbook: iscsi-discovery-login.yaml
  #- import_playbook: enable-multipath.yaml
