---
- name: Create volume on FlashArray
  hosts: cloudblockstore
  connection: local
  gather_facts: no
  vars_files:
  - ./secrets.yaml
  collections:
  - purestorage.flasharray
  
  tasks:
    - name: create new 1TB volume
      purefa_volume:
        name: "{{ volname }}"
        size: 1T
        fa_url: "{{ fa_url }}"
        api_token: "{{ vault_api_token }}"
        state: present
      register: volumes

    - name: print volume name
      debug:
        var: volumes
