---
- hosts: ubuntu
  become: true
  gather_facts: yes

  tasks:

        - name: Create a mount point for the volume
          shell:
            cmd: mkdir /mnt/"{{ volumes.json }}"

        - name: Create a mount point for the volume
          shell: 
            cmd: mkfs.ext4 
