---
- hosts: "{{ ansible_inventory_hostname }}"
  become: true
  gather_facts: yes

  tasks:

        - name: Install open-iscsi package
          apt: name=open-iscsi update_cache=yes state=latest force_apt_get=yes
          register: open_iscsi
          when: ansible_distribution == 'Ubuntu'

        - debug:
            var: open_iscsi

# open-iscsi is installed by default on SLES15.2 and openSUSE15.2

        - name: Restart iscsid service
          shell:
            cmd: systemctl restart iscsid.service
          register: iscsidrestart

        - name: Check iscsid status
          shell:
            cmd: systemctl status iscsid.service
          register: iscsidstatus

        - debug:
            var: iscsidstatus.stdout_lines

        - name: Collect Initiator IQN
          shell:
            cmd: cat /etc/iscsi/initiatorname.iscsi | grep InitiatorName= | sed 's/=/ /' | awk '{print $2}'
          register: localiqn

        - set_fact:
            iqn: "{{ localiqn }}"
            cacheable: yes

        - name: "Print IQN from hostvars"
          debug:
            msg: "{{ hostvars[ansible_inventory_hostname]['iqn']['stdout'] }}"
